grpc/grpc-kotlin

example/build.gradle
example/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldClient.kt
example/src/main/kotlin/io/grpc/examples/helloworld/HelloWorldServer.kt
example/src/main/proto/helloworld.proto

@lowasser could you review this PR? /cc @bshaffer @thisisnotapril

Add Hello World example

---

build.gradle

Add the Dokka plugin to Gradle.

---

examples/src/main/proto/hello_world.proto

(Note the file rename too.)
cc @bshaffer

Hello world proto cleanup

---

examples/src/main/proto/route_guide.proto

Route-guide example proto cleanup

---

examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideClient.kt

RouteGuideClient: drop use of custom Printer

---

examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideClient.kt

Add helper method `generateRoutePoints()` that returns a `Flow<Point>`.

RouteGuideClient: eliminate launch from recordRoute()

---

compiler/build.gradle
stub/build.gradle

fix: switches to implementation from compile for grpc-kotlin-stub

---

build.gradle
compiler/build.gradle
compiler/src/main/java/io/grpc/kotlin/generator/GrpcClientStubGenerator.kt
compiler/src/main/java/io/grpc/kotlin/generator/GrpcCoroutineServerGenerator.kt
compiler/src/test/java/io/grpc/kotlin/generator/GreeterCoroutineImplBase.expected
compiler/src/test/java/io/grpc/kotlin/generator/GreeterCoroutineStub.expected
compiler/src/test/java/io/grpc/kotlin/generator/GrpcClientStubGeneratorTest.kt
compiler/src/test/java/io/grpc/kotlin/generator/HelloWorldProtoGrpcKt.expected
examples/build.gradle
stub/build.gradle

- gets tests running on `gradle test`
- fixes the tests
- Adds test logging output (so this won't happen again)

Get tests running again

---

README.md

I'm going for a simple README for this first release. We can add other information later, as needed. @bshaffer let me know what you think.

Update README for first release

---

README.md

README: add note about use of Java protoc plugin

---

examples/build.gradle

cleanup build

---

build.gradle
compiler/build.gradle
gradle/wrapper/gradle-wrapper.properties

add jdk 7 mins - fixes #84

---

README.md

Update link to API reference docs

---

.github/workflows/bazel.yml

Bazel actions

---

BUILDING.md
CONTRIBUTING.md
README.md

This adds instructions per our discussion earlier this week (06/16). I believe that we agreed that this would be sufficient to close #17.

Add build instructions

---

examples/src/main/proto/hello_world.proto

Use canonical version of `hello_world.proto`

---

build.gradle
stub/src/test/java/io/grpc/kotlin/CoroutineContextServerInterceptorTest.kt

feat: automate maven publish

---

build.gradle

prepare for the release of v0.2.0
depends on #173

chore: support for snapshot URL

---

compiler/build.gradle
compiler/stub.sh
examples-android/common/build.gradle.kts
examples/build.gradle.kts
interop_testing/build.gradle
stub-lite/build.gradle
stub/build.gradle

- addresses #92 
- This may address #98

feat: use jar for protoc

---

build.gradle
examples-android/build.gradle.kts
examples-android/common/build.gradle.kts
examples/build.gradle.kts

v0.2.0 has been published! We can now merge this and tag the release!

chore: prepare v0.2.0

---

build.gradle
examples/build.gradle.kts

- dependency tree for stub-lite (#199)
- correct capitalization of proto files which don't follow the style guide (#189)
- GraalVM example (#187)
- organize examples directory (#183)

chore: prepare v0.2.1

---

stub/src/main/java/io/grpc/kotlin/ClientCalls.kt
stub/src/test/java/io/grpc/kotlin/ClientCallsTest.kt

Copy the metadata in each flow collection for server-streaming RPCs

---

examples/client/build.gradle.kts

fixed application name in client

---

compiler/src/main/java/io/grpc/kotlin/generator/GrpcClientStubGenerator.kt
compiler/src/main/java/io/grpc/kotlin/generator/GrpcCoroutineServerGenerator.kt

Mark deprecated service methods with @Deprecated.

---

gradle.properties
gradle/wrapper/gradle-wrapper.properties
stub/build.gradle.kts

Upgrade to gradle 9 + dokka 2.

---

.github/workflows/publish.yaml

Disable attestation in publish.yaml workflow.
