grpc/grpc-kotlin

- examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideClient.kt
This makes it a bit easier to explain the code in the tutorial.
> RouteGuideClient: simplify base constructor

- examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideClient.kt
As indicated in the proto file, "Points are represented as latitude-longitude pairs in the E7 representation".
> RouteGuideClient: ensure degrees are in E7 format

- examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideClient.kt
- examples/src/main/kotlin/io/grpc/examples/routeguide/RouteGuideServer.kt
- In the client:
- Dropped `launch`
- Created a `generateOutgoingNotes()` helper method that returns a Flow<RouteNote>. 
- Added a "Last Message" route note at 0,0 to make the output at least a bit more interesting
- Added a 500 msec delay after a note is emitted on the client side so that we can see the interplay between the client and the server.
- Only reformatting changes in `RouteGuideServer.kt`
> RouteGuideClient: route chat changes

- build.gradle
- src/main/dist/protoc-gen-grpc-kotlin
- src/main/dist/protoc-gen-grpc-kotlin.bat
Adds a new jar to the distribution (`grpc-kotlin-[version]-protoc.jar`) which is invoked by protobuf
This will create the following distribution files:
_Files the protoc gradle plugin uses to generate from protos_
- grpc-kotlin-0.1-linux-aarch_64.exe
- grpc-kotlin-0.1-linux-x86_32.exe
- grpc-kotlin-0.1-linux-x86_64.exe
- grpc-kotlin-0.1-osx-x86_64.exe
- grpc-kotlin-0.1-windows-x86_32.exe
- grpc-kotlin-0.1-windows-x86_64.exe
_The FAT JAR wrapped by the above scripts_
- grpc-kotlin-0.1-protoc.jar
_The library source_
- grpc-kotlin-0.1.jar
- grpc-kotlin-0.1.pom
> fix: separates protoc plugin fat jar from the source jar

- compiler/build.gradle
This changes the `protoc-gen-grpc-kotlin` pom to be marked as `<scope>compile</scope>` instead of `<scope>runtime</scope>`
> switching back to compile for compiler dependencies

- README.md
Add "/JVM" qualification to links into grpc.io pages, so that the link names match the page titles they are referencing.
> Add "/JVM" qualification to link names

- examples/src/main/proto/hello_world.proto
- examples/src/main/proto/route_guide.proto
Something I was tempted to do when I made a first pass to cleanup the proto files but didn't. I was re-inspired to do so by https://github.com/grpc/grpc.io/pull/184.
cc @bshaffer @jamesward
> Proto files, minor cleanup

- stub/src/main/java/io/grpc/kotlin/ServerCalls.kt
- stub/src/test/java/io/grpc/kotlin/ServerCallsTest.kt
> Make sure trailers from a StatusException propagate to the client.

- stub/src/main/java/io/grpc/kotlin/StubFor.kt
This gRPC-Kotlin project is really awesome. ❤️
Motivation:
Armeria is going to early adopt gRPC-Kotlin by our users' requests.
https://github.com/line/armeria/pull/2669
Armeria gRPC-Java client access `ServiceDescriptor` via reflection.
I think we can access to the original gRPC-Java stub via `StubFor` annotation in coroutine stub.
Modifications:
- Change AnnotationRetention from `BINARY` to `RUNTIME`
Result:
Better interop between Armeria and gRPC-Kotlin 😀
> Make StubFor access via reflection

- .travis.yml
- settings.gradle
- stub-lite/build.gradle
- copied `stub/build.gradle` to `stub-lite/build.gradle`
- Added `stub-lite` as a new package `grpc-kotlin-stub-lite`
- removed `testImplementation` 
- removed `protobuf`
- changed the dependency on `grpc-protobuf` to `grpc-protobuf-lite`
This addresses #80
> Add grpc-kotlin-stub-lite

- README.md
> docs: adds grpc-kotlin-stub-lite to readme

- build.gradle
- stub-lite/build.gradle
- stub/build.gradle
Addresses #73 
- Ensures javadoc is generated for `grpc-kotlin-stub`
- Removes javadoc generated for `grpc-kotlin-stub-lite`
- Only publish javadoc when running on Java 8 (see https://github.com/Kotlin/dokka/issues/294)
> fix: javadoc generation for grpc-kotlin-stub and grpc-kotlin-stub-lite

- compiler/src/main/java/io/grpc/kotlin/generator/TopLevelConstantsGenerator.kt
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/ProtoMethodName.kt
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/ProtoMethodNameTest.kt
- compiler/src/test/proto/testing/rpc_name_contains_underscore.proto
Fix for #94
Added underscore in method name support.
Also added example of proto file and test for new behavior.
> Fix problem with underscores in rpc names

- stub-lite/build.gradle
> fix: excludes grpc-protobuf in grpc-kotlin-stub-lite

- examples-android/README.md
Best [reviewed by ignoring white-space diffs](https://github.com/grpc/grpc-kotlin/pull/176/files?w=1).
Closes #175
> Example README: replace deprecated ANDROID_HOME with ANDROID_SDK_ROOT

- examples/README.md
This PR is **best reviewed while ignoring** [whitespace diffs](https://github.com/grpc/grpc-kotlin/pull/190/files?w=1).
Main changes:
- Link to Quick start and Basics tutorial pages.
- In section explaining the folder organization, link to each folder
- For examples other than hello-world and route-guide, collapse example details under `<details>` element. This is what that section looks like collapsed:
> <img src="https://user-images.githubusercontent.com/4140793/96523836-b34a5000-1244-11eb-9f44-0af4d4cb6a50.png" width=350>
Note that I'll (hopefully soon) be adding a Kotlin-Android Quick start to grpc.io. So the detailed instructions that are in this file will be relocated.
> Examples README rework: refer to grpc.io doc etc

- examples/android/src/main/kotlin/io/grpc/examples/helloworld/MainActivity.kt
- examples/android/src/main/res/layout/activity_main.xml
- examples/android/src/main/res/values/strings.xml
Screenshot:
> <img width="400" alt="Screen Shot 2020-10-21 at 12 08 54" src="https://user-images.githubusercontent.com/4140793/96748343-688d1d00-1397-11eb-8872-064fea1c2bdb.png">
Changes:
- Rename button
- Change server response layout. I find that this more clearly separates the server response text (which can be multiline in the case where we "say hello again") from the label "server response".
- Other UI tweaks
These updates are in preparation for the new Kotlin Android Quick start, https://github.com/grpc/grpc.io/issues/468.
> Android example: minor updates in prep for Quick start page creation

- examples/stub-android/build.gradle.kts
- examples/stub-lite/build.gradle.kts
- examples/stub/build.gradle.kts
Depends on #199 and a `0.2.1` release
> switch examples to correct stub-lite usage

- build.gradle
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/CodeGenerators.kt
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/BUILD.bazel
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/OptionalProto3FieldTest.kt
- compiler/src/test/proto/testing/BUILD.bazel
- compiler/src/test/proto/testing/test_proto3_optional.proto
- interop_testing/build.gradle
Currently, java proto3 compiler supports optional fields. But unfortunately, Kotlin grpc compiler fails to compile such fields. There is a small change based on the [docs](https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md). 
As protobuf supports the feature since version 3.13, I updated protobuf and grpc version in the gradle build script.
> support proto3 optional fields

- build.gradle
Currently the interop tests throw an error on ARM that it cannot find the Conscrypt library.  This is fixed in https://github.com/grpc/grpc-java/commit/b5a0d14da7d04e73c40572c341d2a64ba99db328 but we need to update to the latest version of gRPC to get it.
Related to #229, but that build is not passing for unknown reasons.
> fix: update to latest grpc version so this runs on ARM

- compiler/src/main/java/io/grpc/kotlin/generator/GrpcClientStubGenerator.kt
- stub/src/test/java/io/grpc/kotlin/GeneratedCodeTest.kt
Addresses #224.  Users generally shouldn't use this, but it's hard to get any other way, so let's put it back in.
> Restore metadata support to generated clients

- stub/src/main/java/io/grpc/kotlin/AbstractCoroutineServerImpl.kt
This fixes #261 
`val context` is marked as `open` with this PR in order to allow overriding it
> Open context val in order to allow overriding

- stub/src/main/java/io/grpc/kotlin/ServerCalls.kt
- stub/src/test/java/io/grpc/kotlin/ServerCallsTest.kt
Addresses #272 (see the issue for more background).
This change makes `grpc-kotlin` more consistent with the behaviour of `grpc-java` and `grpc-go`, which don't write the HTTP/2 headers until the first response frame is sent. Current behaviour sends an empty header frame immediately, which can force downstream proxies (namely Envoy) to commit the response, which disables retry behaviour.
> Defer writing headers until the first message stanza is sent

- stub/src/main/java/io/grpc/kotlin/ServerCalls.kt
- stub/src/test/java/io/grpc/kotlin/ServerCallsTest.kt
Before this commit, passing a CoroutineContext with a Job to ServiceImplBase's constructor ended up in the entirety of context's job being cancelled (#302).
> ServerCalls: cancel only the request's Job

- compiler/src/main/java/io/grpc/kotlin/generator/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/testing/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/util/graph/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/util/sort/BUILD.bazel
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/BUILD.bazel
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/testing/BUILD.bazel
- examples/client/src/main/kotlin/io/grpc/examples/animals/BUILD.bazel
- examples/client/src/main/kotlin/io/grpc/examples/helloworld/BUILD.bazel
- examples/client/src/main/kotlin/io/grpc/examples/routeguide/BUILD.bazel
- examples/native-client/src/main/kotlin/io/grpc/examples/helloworld/BUILD.bazel
- examples/server/src/main/kotlin/io/grpc/examples/animals/BUILD.bazel
- examples/server/src/main/kotlin/io/grpc/examples/helloworld/BUILD.bazel
- examples/server/src/main/kotlin/io/grpc/examples/routeguide/BUILD.bazel
- examples/stub/src/main/kotlin/io/grpc/examples/routeguide/BUILD.bazel
- kt_jvm_grpc.bzl
- stub/src/main/java/io/grpc/kotlin/BUILD.bazel
- stub/src/test/java/io/grpc/kotlin/BUILD.bazel
As of rules_kotlin v1.5.0-beta-3, its JVM rules should be imported from
jvm.bzl, not kotlin.bzl, to prevent a noisy warning:
https://github.com/bazelbuild/rules_kotlin/blob/v1.5.0-beta-3/kotlin/kotlin.bzl
> Load rules_kotlin rules from jvm.bzl

- kt_jvm_grpc.bzl
As of Bazel 4, protoc and most tools are dependend on via the exec
configuration rather than the host configuration. By also using the exec
transition in grpc_kotlin, unnecessary (and very costly) rebuilds of
protoc can be prevented.
> Depend on tools in the exec configuration

- compiler/src/main/java/io/grpc/kotlin/generator/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/testing/BUILD.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/protoc/util/graph/BUILD.bazel
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/BUILD.bazel
- compiler/src/test/java/io/grpc/kotlin/generator/protoc/testing/BUILD.bazel
- stub/src/main/java/io/grpc/kotlin/BUILD.bazel
- stub/src/test/java/io/grpc/kotlin/BUILD.bazel
Fixes #298 by replacing explicit `@maven` repository references in `BUILD.bazel` files with individual repository references.
> Remove hardcoded references to @bazel

- repositories.bzl
- stub/src/main/java/io/grpc/kotlin/BUILD.bazel
Hi folks,
In my team Bazel project we use grpc-kotlin and we had some compilation issues because some classes from `org.jetbrains.kotlinx:kotlinx-coroutines-core` have been moved into `org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm`.
We tried to change the depedencies into a forked project and it seems to be working fine for us.
This PR contains the changes we made.
> Add kotlinx-coroutines-core-jvm dependency

- kt_jvm_grpc.bzl
While the Kotlin layer itself doesn't change depending on the flavor (normal or lite), the underlying Java generated library does. This effectively just selects either a `java_lite_proto_library` or a `java_proto_library` depending on the flavor, everything else remains the same.
> Support generating lite protos with Bazel

- interop_testing/src/main/java/io/grpc/testing/integration/AbstractInteropTest.kt
- stub/src/main/java/io/grpc/kotlin/ClientCalls.kt
When streaming call is cancelled it's handled in `sender` coroutine (lines 311-319). Both client call cancellation (line 316) and failure propagation (line 317) eventually reach the listener `onClose` callback (where `responses` flow is closed), but which one reaches the place first is racy. When failure propagation reaches the callback first, the flow is cancelled with cancellation exception (expected). But if the client call cancel reaches the callback first, the flow is cancelled with GRPC status exception (unexpected).
This change recovers the cancellation from GRPC status exception if it was the cause to make the behavior deterministic and aligned with expectations.
I don't know how to test this change reliably. I succeeded to reproduce the issue via slow emulator tests only with …
> Recover cancellation when close responses flow

- kt_jvm_grpc.bzl
These names are chosen to mirror the action mnemonics in the kt_jvm_grpc_library implementation.
> Provide action mnemonics for kt_jvm_proto_library implementation.

- kt_jvm_grpc.bzl
running with run_shell on windows results in arguments not being passed properly to zipper. running with `run_shell` calls `bash -c zipper.exe $@ [args]` but does not put quotes around the string passed to bash -c. This means that zipper does not get any arguments passed to it and the step fails. This change makes it so we can run the zipper binary directly and ensures that arguments are passed correctly. It should work on any platform.
> Migrate run command to work on a windows machine

- examples/stub/build.gradle.kts
The stub example project explicitly disables sourceSets as the generated files do not pass ktlint checks. For new developers using IntelliJ this can be not very clear because the IDE does not recognize the generated files. This simple PR just disables the ktlint checks on generated directories.
> Enable sourceSets in the stub example project

- compiler/README.md
Adding missing dash ('-') to a comment for Maven pluging instructions readme file
> [README][fix] Adding missing character on readme

- .github/workflows/gradle.yml
Resolve  #394 
Update `.github/workflows/gradle.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=stdout::${OUTPUT//$'\n'/'%0A'}"
```
**TO-BE**
```yaml
echo "stdout=${OUTPUT//$'\n'/'%0A'}" >> $GITHUB_OUTPUT
```
> Replace deprecated command with environment file

- stub/src/main/java/io/grpc/kotlin/ServerCalls.kt
- stub/src/test/java/io/grpc/kotlin/ServerCallsTest.kt
This fixes the issue where stack trace logging interceptors fail to log the relevant context when upstream handlers throw a StatusException.
Relates to #299
> fix(ServerCalls): Ensure failure cause is propagated in Status to interceptors

- repositories.bzl
Previously bazel builds would produce the following warning: ' com.google.guava:guava has multiple versions 29.0-android, 32.0.1-android'.
This commit updates the guava version to be consistently 32.0.1
> Bazel: update to use guava 32.0.1 consistently.

- compiler/README.md
There is a missing double quotes (") in compiler documentation (Manual `protoc` Usage) and when used, produces the following error:
```bash
protoc-gen-grpc-kotlin.sh: line 4: unexpected EOF while looking for matching `"'
protoc-gen-grpc-kotlin.sh: line 5: syntax error: unexpected end of file
```
> FIXED: Missing double quotes in compiler docs leading to error.

- stub/src/test/java/io/grpc/kotlin/ServerCallsTest.kt
Something I noticed when writing https://github.com/grpc/grpc-kotlin/pull/456 is that with the new branch capturing Status exceptions, the existing regression test that I modified to throw a non-status exception is no longer sufficient to ensure the stack trace is available to the interceptor. Concretely, `Status.fromThrowable(exception)` will always have `exception` as the cause of the status so long as `exception` is not a Status exception _and has no Status exception in its causal chain_.
This PR adds a test covering that case; without the extra `withCause` call this test will fail.
> Add regression test capturing need for `withCause` call

- interop_testing/src/main/java/io/grpc/testing/integration/TestServiceClient.kt
On the Java side we are going to be removing `enableFullStreamDecompression()` from `ManagedChannelBuilder` as the feature was never implemented.
> Remove full_stream_decompression from TestServiceClient.kt

- MODULE.bazel
- compiler/src/main/java/io/grpc/kotlin/generator/BUILD.bazel
- examples/client/src/main/kotlin/io/grpc/examples/animals/BUILD.bazel
- examples/client/src/main/kotlin/io/grpc/examples/helloworld/BUILD.bazel
- examples/client/src/main/kotlin/io/grpc/examples/routeguide/BUILD.bazel
- examples/native-client/src/main/kotlin/io/grpc/examples/helloworld/BUILD.bazel
- examples/server/src/main/kotlin/io/grpc/examples/animals/BUILD.bazel
- examples/server/src/main/kotlin/io/grpc/examples/helloworld/BUILD.bazel
- examples/server/src/main/kotlin/io/grpc/examples/routeguide/BUILD.bazel
- kt_jvm_grpc.bzl
- stub/src/main/java/io/grpc/kotlin/BUILD.bazel
- stub/src/test/java/io/grpc/kotlin/BUILD.bazel
> Use @grpc-java directly.

- .github/workflows/publish.yaml
> Add a simple publish to BCR workflow.

- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
> Add a simple .bcr directory.
